module.exports = {
  "Zain": "زين"
  "Overview": "نظرة عامة"
  "Billing": "الفواتير"
  "Call Trace": "تتبع المكالمات"
  "Payments": "المدفوعات"
  "Pay now": "دفع الآن"
  "Settings": "إعدادات"
  "Settings & Support": "الإعدادات والدعم"
  "SMS sent": "أرسلت الرسالة"
  "This app doesn’t have permission to send an sms, please change the settings in your phone or copy the code to clipboard and send to ‘99998’ manually.": "لا يملك هذا التطبيق الإذن بإرسال رسالة قصيرة، يرجى تغيير إعدادات الهاتف أو نسخ الرمز إلى الحافظة وإرسالها يدويا إلى 99998."
  "Pay Now": "ادفع الآن"
  "KD": "دينار كويتي"
  "Previous bill amount": "الفاتورة السابقة"
  "Current month charges": "رسوم الشهر الحالي"
  "Total amount": "الفاتورة الإجمالية"
  "Due": "واجب الأداء"
  "Pay now": "ادفع الآن"
  "Billing history": "تاريخ الفواتير"
  "Billing older then 6 months is available in Stores.": "الفواتير الأقدم من 6 أشهر متوفرة الآن في المتاجر"
  "Go to Store Locator": "انتقل إلى فروعنا"
  "Billing": "الفواتير"
  "Welcome to<br>Call Trace!": "مرحبا بك في<br>متتبع الإتصال!"
  "Call trace is a simple tool that allows you to check your recent calls with the numbers held in your contact list.": "تتبع الإتصال هوأداة بسيطة تسمح لك بالتحقق من مكالماتك الأخيرة مع الأرقام الموجودة في قائمة الأسماء بهاتفك"
  "Your contacts are not sent to us and remain on your phone.": "لم يتم إرسال قائمة الأسماء الخاصة بك إلينا، وظلت في هاتفك"
  "Start Now": "ابدأ الآن"
  "Date (from)": "التاريخ (من)"
  "Date (to)": "التاريخ (إلى)"
  "Time (from)": "الوقت (من)"
  "Time (to)": "الوقت (إلى)"
  "Price (from)": "الثمن (من)"
  "Price (to)": "الثمن (إلى)"
  "Calls": "المكالمات"
  "Export as PDF": "تصدير بصيغة PDF"
  "Messages": "الرسائل"
  "Data": "معطيات"
  "Local": "Local"
  "Roaming": "تجوال"
  "International": "دولي"
  "Select news type": "حدد نوع الأخبار"
  "Press Releases": "نشرات صحفية"
  "Offers": "العروض"
  "Social Media": "وسائل الإعلام الاجتماعية"
  "News": "الأخبار"
  "News Filter": "أخبار مختارة"
  "All accounts": "جميع الحسابات"
  "Internet Services": "خدمات الإنترنت"
  "Please select an account for more information.": "الرجاء اختيار حساب لمزيد من المعلومات"
  "Previous Month": "الشهر السابق"
  "Pay now": "ادفع الآن"
  "Add GB": "إضافة GB"
  "Add Internet Plan": "إضافة خطة الإنترنت"
  "Other (Custom Amount)": ""
  "Amount must not be empty": "يجب ألا يترك المبلغ فارغا"
  "Amount must not be 0": "يجب ألا يكون المبلغ 0"
  "Invalid transfer amount": "مبلغ التحويل غير صالح"
  "Choose an account": "اختار حسابا"
  "Custom amount must not be blank": "يجب أن لا يترك المبلغ المحدد فارغا"
  "Custom amount must not be 0": ""
  "Invalid custom value": ""
  "Email cannot be empty": "البريد الإلكتروني لا يمكن أن يترك فارغا"
  "Invalid email": "البريد الإلكتروني غير صالح"
  "Choose an account": "اختار حسابا"
  "Select an amount": "حدد مبلغا"
  "Custom amount must not be 0": "يجب أن لا يكون المبلغ المحدد 0"
  "Invalid custom value": "القيمة المحددة غير صالحة"
  "Email cannot be empty": "البريد الإلكتروني لا يمكن أن يترك فارغا"
  "Invalid email": "البريد الإلكتروني غير صالح"
  "Select an amount": "حدد مبلغا"
  "Email cannot be empty": "البريد الإلكتروني لا يمكن أن يترك فارغا"
  "Invalid email": "البريد الإلكتروني غير صالح"
  "Balance": "رصيد حساب"
  "Pay everything": "دفع كل شيء"
  "Custom amount": "المبلغ المحدد"
  "Balance": "رصيد حساب"
  "Pay current amount": "دفع المبلغ الحالي"
  "Account number": "رقم الحساب"
  "Pay everything": "دفع كل شيء"
  "Input custom amount (KD)": "ادخال مبلغ محدد (دينار كويتي)"
  "Email Address (for receipt)": "عنوان البريد الإلكتروني (للمستلم)"
  "eeZee Recharge": "تعبئة eeZee"
  "For me": "لأجلي"
  "Save Recharge Card": "حفظ بطاقة التعبئة"
  "Account number": "رقم الحساب"
  "Enter amount (KD)": "أدخل المبلغ (دينار كويتي)"
  "Email Address (for receipt)": "عنوان البريد الإلكتروني (للمستلم)"
  "The recharge card will be available to you to save or send (via SMS) after payment.": "سوف تكون بطاقة التعبئة متاحة لك للحفظ أو للإرسال (عبر sms) بعد الدفع"
  "QuickPay": "الدفع السريع"
  "Payments": "المدفوعات"
  "Continue": "متابعة"
  "Make Payment Now": "إجراء الدفع الآن"
  "Cancel": "إلغاء"
  "Step %s of %s: Submit Data": "خطوة %s من %s: إرسال البيانات"
  "Credit Transfer": "تحويل الرصيد"
  "Transfer credit between Zain users quickly and easily by filling out the form below.": "يمكن تحويل الرصيد بين مستخدمي زين بسرعة وسهولة وذلك عن طريق ملء الاستمارة أدناه"
  "Who to transfer credit to?": "إلى من سترسل الرضيد"
  "Credit Transfer": "تحويل الرصيد"
  "Mobile number": "رقم الهاتف"
  "Input amount (KD)": "ادخال مبلغ (دينار كويتي)"
  "Transfer Credit": "تحويل الرصيد"
  "Step %s of %s: Copy the Text": "خطوة %s من %s: نسخ النص"
  "Or tap to send as SMS": "أو اضغط للإرسال ك SMS"
  "Done": "تم"
  "Category": "فئة"
  "Fee": "الرسوم"
  "Recurrence": "تكرار"
  "Or tap to send as SMS": "أو اضغط للإرسال ك SMS"
  "Services": "خدمات"
  "No services": "لا توجد خدمات"
  "Activated services": "الخدمات المفعلة"
  "Available services": "الخدمات المتوفرة"
  "Or activate in person in one of our branches.": "أو فعله شخصيا في أحد فروعنا"
  "Go to Store Locator": "انتقل إلى فروعنا"
  "Settings & Support": "الإعداد والدعم"
  "Language selector": "اختيار اللغة"
  "English": "الإنجليزية "
  "Arabic": "العربية"
  "Save language settings": "حفظ إعدادات اللغة"
  "Contact Us": "تواصل معنا"
  "Email Us": "راسلنا بالبريد الإلكتروني"
  "Live Chat": "الدردشة الحية"
  "Call Us": "اتصل بنا"
  "View Tutorial": "عرض تعليمي"
  "Store details": "متجر المعلومات"
  "Address": "العنوان"
  "Phone": "رقم الهاتف"
  "Hours": "أوقات العمل"
  "Open in Maps": "البحت في الخرائط"
  "Store Locator": "الفروع"
  "Find a store near you": "_ابحث عن متجر بالقرب منك"
  "No stores": "لا متاجر"
  "Username must not be empty": "يجب ألا يترك اسم المستخدم فارغا"
  "Special characters are not allowed in Username": "لا يسمح بلأحرف الخاصة في اسم المستخدم"
  "Password must not be empty": " يجب ألا تترك كلمة السر فارغة"
  "Number must not be empty": " لا يجب أن يترك رقم الهاتف فارغا"
  "Number cannot contain special characters": "لا يمكن أن يحتوي رقم الهاتف على أحرف خاصة"
  "Reset token must not be empty": "لا يجب أن تترك إعادة تعيين الرمز المميز فارغة"
  "Reset token must be 5 characters long": "يجب أن يحتوي إعادة تعيين الرمز المميز على 5 أحرف"
  "Special characters are not allowed in the Reset Token": "لا يسمح بلأحرف الخاصة في إعادة تعيين الرمز االمميز"
  "Password must not be empty": "يجب ألا تترك كلمة السر فارغة"
  "Password is too short, it should be minimum 6 characters.": "كلمة السر هي قصيرة جدا، يجب أن تحتوي على 6 أحرف على الأقل"
  "Your passwords do not match.": "كلمات السر الخاصة بك غير متطابقة"
  "Number must not be empty.": "لا يجب أن يترك رقم الهاتف فارغا"
  "Invalid phone number.": "رقم الهاتف غير صالح"
  "Verification code must not be empty.": "لا يجب أن يترك رمز التحقق فارغا"
  "Invalid verification code.": "رمز التحقق غير صالح"
  "Verification code must not be empty": "لا يجب أن يترك رمز التحقق فارغا"
  "Password must not be empty": "يجب ألا تترك كلمة السر فارغة"
  "Your passwords do not match.": "كلمات السر الخاصة بك غير متطابقة"
  "Reset token was re-sent to %s": "أعيد إرسال إعادة تعيين الرمز المميز إلى %s"
  "Verifying...": "التحقق..."
  "Login": "تسجيل الدخول"
  "Reset token was re-sent to %s": "أعيد إرسال إعادة تعيين الرمز المميز إلى %s"
  "News": "أخبار"
  " QuickPay": "الدفع السريع"
  " Branch Locator": "تحديد الفرع"
  "Credit Transfer": "تحويل الرصيد"
  "Register": "تسجيل"
  "Forgot Details?": "نسيت التفاصيل"
  "Completed": "تم"
  "Success": "ناجح"
  "Log in to my account": "تسجيل الدخول إلى حسابي"
  "Step %s of %s: Input Username": "خطوة %s من %s: إدخال اسم المستخدم"
  "What is your mobile number?": "ماهو رقم هاتفك"
  "Send my pincode": "أرسل رقمي السري"
  "Step %s of %s: Create new Password": "خطوة %s من %s: إنشاء كلمة سر جديدة"
  "Create new Password": "إنشاء كلمة سر جديدة"
  "Change my password": "تغيير كلمة السر"
  "Step %s of %s: Reset token": "خطوة %s من %s: إعادة تعيين الرمز المميز"
  "Input reset token": "إدخال رمز إعادة تعيين"
  "Next step": "الخطوة التالية"
  "Resend code": "إعادة إرسال الرمز"
  "Step %s of %s: Set up a password": "خطوة %s من %s: إنشاء كلمة السر"
  "Password details": "تفاصيل كلمة السر"
  "Register": "تسجيل"
  "Go back": "العودة"
  "Step %s of %s: Registered Address": "خطوة %s من %s: العنوان المسجل"
  "Mailing info": "المعلومات البريدية"
  "select city": "اختر المدينة"
  "select area": "اختر المنطقة"
  "block": "حي"
  "street": "شارع "
  "avenue": "الجادة"
  "building #": "مبنى #"
  "floor": "طابق"
  "apt #": "الشقة"
  "Next step": "الخطوة التالية"
  "Go back": "العودة"
  "Step %s of %s: Mobile Confirmation": "خطوة %s من %s: تأكيد الهاتف"
  "Create an Account": "إنشاء حساب"
  "Just follow our simple steps to start accessing a whole world of extra features": "ما عليك سوى اتباع خطواتنا البسيطة للوصول إلى العالم كله من الميزات الإضافية"
  "Mobile number": "رقم الهاتف"
  "enter mobile number": "أدخل رقم الهاتف"
  "A verification code will be sent to your phone needed to complete the next step.": "سيتم إرسال رمز التحقق إلى هاتفك لإستكمال الخطوة التالية"
  "Send my verification code": "أرسل رمز التحقق الخاص بي"
  "Completed": "تم"
  "Welcome!": "مرحبا"
  "Your account has been created.": "لقد تم إنشاء حسابك"
  "We've sent you an email to confirm everything.": "لقد أرسلنا إليك رسالة إلكترونية لتأكيد كل شيء"
  "Log in to my account": "تسجيل الدخول إلى حسابي"
  "Step %s of %s: Setting up your Identity": "خطوة %s من %s: إنشاء الهوية الخاصة بك"
  "Account details": "تفاصيل الحساب"
  "enter your civil ID": "أدخل رقم التعريف المدني الخاص بك"
  "choose your log in ID": "اختر هوية تسجيل الدخول الخاصة بك"
  "enter email address": "ادخل عنوان البريد الإلكتروني"
  "I would like to receive special offers": "أود أن أتلقى العروض الخاصة"
  "Next step": "الخطوة التالية"
  "Go back": "العودة"
  "Step %s of %s: Mobile Verification": "خطوة %s من %s: التحقق من الهاتف"
  "Verify Mobile Phone": "التحقق من الهوتف"
  "Input verification code": "إدخال رمز التحقق"
  "Next step": "الخطوة التالية"
  "Resend code": "إعادة إرسال الرمز"
  "Select an account": "اختر حسابا"
  "Log out": "تسجيل الخروج"
  "Store Locator": "الفروع"
  "Overview": "نظرة عامة"
  "Billing": ""
  "Payments": "المدفوعات"
  "News": "أخبار"
  "Services": "خدمات"
  "Settings": "الإعداد"
  "Continue": "متابعة"
  "Account": "الحساب"
  "Unpaid": "غير مدفوع"
  "Verifying...": "جاري التأكد..."
  "Sign In": "تسجيل الدخول"
  "Register": "تسجيل"
  "Overview": "نظرة عامة"

  "register.verificationinfo": "تم إرسال رمز التحقق إلى <strong>%s</ STRONG>. أدخل رمز في الحقل أدناه للمتابعة."
}
